name: deploy website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./
# name: My Frist Github Action
# on: [push]
# jobs:
#   build-app:
#     runs-on: ubuntu-latest
#     env:
#         PROJECT_ID: ${{secrets.PROJECT_ID}}
#         ORG_ID: ${{secrets.ORG_ID}}
#         VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#             node-version: '17'
#       - name: Add Node Module
#         run : npm install
#       - name: Build The Project
#         run: npm run build
#       - name: set vercel cli
#         run: |
#           cd build
#           mkdir .vercel
#           cd .vercel
#           touch project.json
#           echo '{\"orgId\":\"$ORG_ID\","\projectId\":\"$PROJECT_ID\"}' > project.json
#           cat project.json
#       - name: Deploying The Project
#         run: npm run deploy
#       - name: Finished build
#         run : echo "Hurry"
      
